version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: mcp_backend
    image: studio-base
    command: >
      sh -c "
      pixi run frontend_build &&
      pixi run backend_no_docker
      "
    ports:
      - "10090:10090"
    env_file:
      - .env
    environment:
      - OTEL_SERVICE_NAME=llm_worker
      - LLM_WORKER_PORT=9200
      - MCP_USE_OAUTH=false
      - MCP_TOOL_CONFIG_PATH=/app/scepa_tools.json
      - MCP_CALLBACK_PORT=9200
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mcp_server_scepa_studio_net

networks:
  mcp_server_scepa_studio_net:
    driver: bridge
    external: true  # Reference the external network from MCP stack