worker_processes auto;

events { worker_connections 1024; }

http {

    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;

    # FastAPI backend
    upstream kg_backend {
        server kg-backend:9000;
    }

    resolver 127.0.0.11 ipv6=off;

	upstream authentik_outpost {
		zone upstream_authentik 64k;
		server authentik-outpost-proxy:9000 resolve;
	}



    # Authentik UI
    server {
        listen 80;
        server_name auth.localhost;

        location / {
            proxy_pass http://authentik-server:9000;
        }
    }

    # Protected application
    server {
        listen 80;
        server_name kg.localhost;

        # Forward authentication
        auth_request /authentik;

        # Pass identity headers
        auth_request_set $auth_user $upstream_http_x_authentik_username;
        auth_request_set $auth_email $upstream_http_x_authentik_email;
        proxy_set_header X-Forwarded-User $auth_user;
        proxy_set_header X-Forwarded-Email $auth_email;

        location /authentik {
            internal;
            proxy_pass http://authentik_outpost/outpost.goauthentik.io/auth/nginx;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
        }

        location / {
            proxy_pass http://kg_backend;
        }
    }
}
