/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Knowledge Graph API
 * API for chat-based knowledge graph generation and node context retrieval
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod/mini';

/**
 * @summary Redirect To App
 */
export const RedirectToAppGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * Redirect the user to Authentik for authentication.
 * @summary Login
 */
export const LoginAuthLoginGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * OAuth callback endpoint: retrieves tokens and stores userinfo in session.
 * @summary Callback
 */
export const CallbackAuthCallbackGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * Clear the user's session and log them out.
 * @summary Logout
 */
export const LogoutAuthLogoutGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * Return authenticated user metadata.
 * @summary Me
 */
export const MeMeGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * @summary Get Full Graph
 */
export const GetFullGraphGraphGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * @summary Log Event
 */
export const LogEventLogEventPostBody = /*#__PURE__*/ zod.object({
  "name": /*#__PURE__*/ zod.string(),
  "metadata": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.record(/*#__PURE__*/ zod.string(), /*#__PURE__*/ zod.unknown()))
})

export const LogEventLogEventPostResponse = /*#__PURE__*/ zod.void()


/**
 * Store a PDF under its own sha256 content hash.
 *
 * sha256 is verified server-side against the uploaded bytes and rejected
 * on mismatch, so a given hash always maps to exactly one PDF. Re-uploading
 * the same content under its own hash is a safe no-op. Machine clients
 * only — an authorized application (e.g. scepa-rs) pushes PDFs here after
 * ingesting them.
 * @summary Upload Pdf
 */
export const UploadPdfApiPdfSha256PutParams = /*#__PURE__*/ zod.object({
  "sha256": /*#__PURE__*/ zod.string()
})

export const UploadPdfApiPdfSha256PutBody = /*#__PURE__*/ zod.object({
  "file": /*#__PURE__*/ zod.instanceof(File)
})

export const UploadPdfApiPdfSha256PutResponse = /*#__PURE__*/ zod.unknown()


/**
 * Return the raw PDF bytes stored under sha256.
 *
 * Readable by both authorized applications (API key) and the frontend's
 * PDF viewer (browser session) — unlike upload/delete, which stay
 * machine-only. Responses are cached indefinitely: the identifier is the
 * content's own hash, so it can never point to different bytes later.
 * @summary Get Pdf
 */
export const GetPdfApiPdfSha256GetParams = /*#__PURE__*/ zod.object({
  "sha256": /*#__PURE__*/ zod.string()
})

export const GetPdfApiPdfSha256GetResponse = /*#__PURE__*/ zod.unknown()


/**
 * Delete the PDF stored under sha256. Machine clients only.
 * @summary Delete Pdf
 */
export const DeletePdfApiPdfSha256DeleteParams = /*#__PURE__*/ zod.object({
  "sha256": /*#__PURE__*/ zod.string()
})

export const DeletePdfApiPdfSha256DeleteResponse = /*#__PURE__*/ zod.void()


/**
 * @summary List Sessions
 */
export const listSessionsSessionsGetResponseMessageCountDefault = 0;
export const listSessionsSessionsGetResponseTitleTypeDefault = `adaptive`;
export const listSessionsSessionsGetResponseTitleOverwrittenDefault = false;
export const listSessionsSessionsGetResponseLastTitleMessageCountDefault = 0;

export const ListSessionsSessionsGetResponseItem = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid(),
  "user_id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), listSessionsSessionsGetResponseMessageCountDefault),
  "title_type": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['static', 'adaptive']), listSessionsSessionsGetResponseTitleTypeDefault),
  "title_overwritten": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.boolean(), listSessionsSessionsGetResponseTitleOverwrittenDefault),
  "last_title_message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), listSessionsSessionsGetResponseLastTitleMessageCountDefault)
})
export const ListSessionsSessionsGetResponse = /*#__PURE__*/ zod.array(ListSessionsSessionsGetResponseItem)


/**
 * @summary Create Session
 */
export const createSessionSessionsPostResponseMessageCountDefault = 0;
export const createSessionSessionsPostResponseTitleTypeDefault = `adaptive`;
export const createSessionSessionsPostResponseTitleOverwrittenDefault = false;
export const createSessionSessionsPostResponseLastTitleMessageCountDefault = 0;

export const CreateSessionSessionsPostResponse = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid(),
  "user_id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), createSessionSessionsPostResponseMessageCountDefault),
  "title_type": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['static', 'adaptive']), createSessionSessionsPostResponseTitleTypeDefault),
  "title_overwritten": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.boolean(), createSessionSessionsPostResponseTitleOverwrittenDefault),
  "last_title_message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), createSessionSessionsPostResponseLastTitleMessageCountDefault)
})


/**
 * @summary Get Session
 */
export const GetSessionSessionsSessionIdGetParams = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid()
})

export const getSessionSessionsSessionIdGetResponseSessionMessageCountDefault = 0;
export const getSessionSessionsSessionIdGetResponseSessionTitleTypeDefault = `adaptive`;
export const getSessionSessionsSessionIdGetResponseSessionTitleOverwrittenDefault = false;
export const getSessionSessionsSessionIdGetResponseSessionLastTitleMessageCountDefault = 0;

export const GetSessionSessionsSessionIdGetResponse = /*#__PURE__*/ zod.object({
  "session": /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid(),
  "user_id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), getSessionSessionsSessionIdGetResponseSessionMessageCountDefault),
  "title_type": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['static', 'adaptive']), getSessionSessionsSessionIdGetResponseSessionTitleTypeDefault),
  "title_overwritten": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.boolean(), getSessionSessionsSessionIdGetResponseSessionTitleOverwrittenDefault),
  "last_title_message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), getSessionSessionsSessionIdGetResponseSessionLastTitleMessageCountDefault)
}),
  "messages": /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.object({
  "message_id": /*#__PURE__*/ zod.uuid(),
  "role": /*#__PURE__*/ zod.enum(['ai', 'user']),
  "content": /*#__PURE__*/ zod.string(),
  "created_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true})
}))
})


/**
 * @summary Update Session
 */
export const UpdateSessionSessionsSessionIdPatchParams = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid()
})

export const UpdateSessionSessionsSessionIdPatchBody = /*#__PURE__*/ zod.object({
  "name": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.union([/*#__PURE__*/ zod.string(),/*#__PURE__*/ zod.null()])),
  "title_type": /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.union([/*#__PURE__*/ zod.enum(['static', 'adaptive']),/*#__PURE__*/ zod.null()]))
})

export const updateSessionSessionsSessionIdPatchResponseMessageCountDefault = 0;
export const updateSessionSessionsSessionIdPatchResponseTitleTypeDefault = `adaptive`;
export const updateSessionSessionsSessionIdPatchResponseTitleOverwrittenDefault = false;
export const updateSessionSessionsSessionIdPatchResponseLastTitleMessageCountDefault = 0;

export const UpdateSessionSessionsSessionIdPatchResponse = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid(),
  "user_id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), updateSessionSessionsSessionIdPatchResponseMessageCountDefault),
  "title_type": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['static', 'adaptive']), updateSessionSessionsSessionIdPatchResponseTitleTypeDefault),
  "title_overwritten": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.boolean(), updateSessionSessionsSessionIdPatchResponseTitleOverwrittenDefault),
  "last_title_message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), updateSessionSessionsSessionIdPatchResponseLastTitleMessageCountDefault)
})


/**
 * @summary Activate Session
 */
export const ActivateSessionSessionsSessionIdPostParams = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid()
})

export const activateSessionSessionsSessionIdPostResponseMessageCountDefault = 0;
export const activateSessionSessionsSessionIdPostResponseTitleTypeDefault = `adaptive`;
export const activateSessionSessionsSessionIdPostResponseTitleOverwrittenDefault = false;
export const activateSessionSessionsSessionIdPostResponseLastTitleMessageCountDefault = 0;

export const ActivateSessionSessionsSessionIdPostResponse = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid(),
  "user_id": /*#__PURE__*/ zod.string(),
  "name": /*#__PURE__*/ zod.string(),
  "updated_at": /*#__PURE__*/ zod.iso.datetime({"offset":true}),
  "message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), activateSessionSessionsSessionIdPostResponseMessageCountDefault),
  "title_type": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.enum(['static', 'adaptive']), activateSessionSessionsSessionIdPostResponseTitleTypeDefault),
  "title_overwritten": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.boolean(), activateSessionSessionsSessionIdPostResponseTitleOverwrittenDefault),
  "last_title_message_count": /*#__PURE__*/ zod._default(/*#__PURE__*/ zod.int(), activateSessionSessionsSessionIdPostResponseLastTitleMessageCountDefault)
})


/**
 * @summary Delete Session
 */
export const DeleteSessionSessionsSessionIdDeleteParams = /*#__PURE__*/ zod.object({
  "session_id": /*#__PURE__*/ zod.uuid()
})

export const DeleteSessionSessionsSessionIdDeleteResponse = /*#__PURE__*/ zod.void()


/**
 * @summary Serve Frontend
 */
export const ServeFrontendAppPathGetParams = /*#__PURE__*/ zod.object({
  "path": /*#__PURE__*/ zod.string()
})

export const ServeFrontendAppPathGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * @summary App Root
 */
export const AppRootAppGetResponse = /*#__PURE__*/ zod.unknown()


/**
 * @summary Serve Assets
 */
export const ServeAssetsAssetsPathGetParams = /*#__PURE__*/ zod.object({
  "path": /*#__PURE__*/ zod.string()
})

export const ServeAssetsAssetsPathGetResponse = /*#__PURE__*/ zod.unknown()
