name: Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  qava-test:
    name: QAVA Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.46.0

      - name: Run QAVA tests
        run: pixi run qava_test
